# name: auto publish
# on:
#   push:
#     # main 브랜치에서만 작동합니다.
#     branches: [dev]
#     paths-ignore:
#       - 'README.md'
#       - 'docs/**'

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: executing remote ssh commands using password
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DEV_HOST }}
#           username: ${{ secrets.DEV_USERNAME }}
#           password: ${{ secrets.DEV_PASSWORD }}
#           port: ${{ secrets.DEV_PORT }}
#           script: |
#             cd /home/web/next
#             git pull
#             git pull origin dev
#             npm install
#             npm run build
#             pm2 stop all
#             pm2 start npm --name "next" -- start
